# Generated by Django 2.0 on 2017-12-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(verbose_name='forecast time')),
                ('temperature', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
    ]
