# Generated by Django 2.0 on 2017-12-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourforecast',
            name='civil_time',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
