# Generated by Django 2.0 on 2017-12-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_hourforecast_civil_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourforecast',
            old_name='hour',
            new_name='fct_hour',
        ),
    ]
