# Generated by Django 2.0 on 2018-01-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu',
            new_name='breakfast_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='bright_meal_menu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='brunch_menu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='dinner_menu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='late_night_menu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch_menu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_headings',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
